Repository wecode-bootcamp-korea/15-1st-LineAmigos-backend, pull requests merged in 2020-12, with the labels that each got.

#1 models.py 작성 완료
  lineamigos/settings.py
  lineamigos/urls.py
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20201217_1247.py
  order/migrations/0003_auto_20201217_2012.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/urls.py
  order/views.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20201217_1247.py
  product/migrations/0003_remove_product_sales_quantity.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/urls.py
  product/views.py
  review/__init__.py
  review/admin.py
  review/apps.py
  review/migrations/0001_initial.py
  review/migrations/0002_auto_20201217_1247.py
  review/migrations/__init__.py
  review/models.py
  review/tests.py
  review/urls.py
  review/views.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20201217_2012.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: Accepted

#4 [모델링] Model 수정, 확인 및 merge 부탁드립니다
  .gitignore
  lineamigos/urls.py
  order/urls.py
  order/views.py
  product/migrations/0004_auto_20201220_1939.py
  product/migrations/0005_auto_20201220_1941.py
  product/models.py
Labels: Status: 리뷰 요청

#2 [Product] 전체, 디테일 View 완료
  .gitignore
  .gitignore.swp
  image 복사본.csv
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20201217_1247.py
  order/migrations/0003_auto_20201217_2012.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20201217_1247.py
  product/migrations/0003_remove_product_sales_quantity.py
  product/urls.py
  product/views.py
  requirements.txt
  review/migrations/0001_initial.py
  review/migrations/0002_auto_20201217_1247.py
  review/urls.py
  review/views.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20201217_2012.py
Labels: Status: Accepted

#3 [User] Add & Revision: 토큰시간 적용 포함 리뷰사항 반영
  .gitignore
  lineamigos/settings.py
  lineamigos/urls.py
  product/urls.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: 리뷰 요청

#6 [Review/views.py]전체 review를 보내주는 view입니다
  lineamigos/settings.py
  review/urls.py
  review/views.py
Labels: Status: 컨플릭트 해결 요청

#7 ADD: RESTful API: review_id
  lineamigos/settings.py
  review/urls.py
  review/views.py
Labels: Status: 리뷰 요청
